### ISSUE TITLE
The chat allows XSS vulnerability

### ISSUE THREAD

**Issue by akarzazi** [ServiceStackApps/Chat#7]
The messages are not encoded.
This message shows popoup to all users :
`<script>alert('e')</script>`

**Comment by mythz** [comment]
Oops :) Should now be fixed with [this commit](https://github.com/NetCoreApps/Chat/commit/d0074173ae57c68d7b58aab3cf74df78875530ce) that's now deployed to http://chat.netcore.io

Definitely something we need to watch out for in future .NET Core Apps as in ASP.NET 4.5 Chat (http://chat.servicestack.net) `<script>alert('e')</script>` gets validated by ASP.NET preventing the request from reaching ServiceStack whereas in .NET Core it doesn't (even on Windows with `.UseIISIntegration()`).

thx for reporting!
